[project]
name = "songs-sense"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "datasets>=4.8.5",
    "fastapi>=0.136.1",
    "flagembedding>=1.4.0",
    "httpx>=0.28.1",
    "lingua-language-detector>=2.2.0",
    "lyricsgenius>=3.12.2",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "pgvector>=0.4.2",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=5.5.1",
    "torch>=2.12.0",
    "uvicorn>=0.47.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.13",
]
